### ISSUE TITLE
link to demo doesn't work in readme

### ISSUE THREAD

**Issue by mbsimonovic** [quasarframework/app-extension-qenv#5]
just click the link

**Comment by hawkeye64** [comment]
I'm not sure why you think it doesn't work.
Go tot this url: https://quasarframework.github.io/app-extension-qenv/
Open your browser dev tools. View console. Expand `Object` on `QEnv Test`, expand `jeff`. 
This is what you get:
![image](https://user-images.githubusercontent.com/10262924/60519503-ef008580-9ca0-11e9-85be-4c1144b576b7.png)

**Comment by corepay** [comment]
![image](https://user-images.githubusercontent.com/48992923/61594124-dd324400-abb5-11e9-85d4-bc4979a2046f.png)


Likely because in your README.md this link:

![image](https://user-images.githubusercontent.com/48992923/61594081-8d537d00-abb5-11e9-9e41-a5542c7f0e12.png)

Goes here:  https://quasarframework.github.io/app-extension-qenv/demo/dist/spa/#/

returning a 404

![image](https://user-images.githubusercontent.com/48992923/61594118-ca1f7400-abb5-11e9-9bb2-712612efeb55.png)

**Comment by nothingismagick** [comment]
Here's the right link:
https://quasarframework.github.io/app-extension-qenv/

**Comment by corepay** [comment]
:) yes thank you I got it - was informing you the link in your readme.md is wrong which was the reason the original poster says the “demo is broken’….

**Comment by nothingismagick** [comment]
In the future @mbsimonovic it would save everyone a lot of work if you would clearly express the issue you are having instead of "just click the link." This is a pretty big ecosystem and a link could be anywhere.

![Screen Shot 2019-07-21 at 18 55 22](https://user-images.githubusercontent.com/35242872/61594199-2a7bd900-abe9-11e9-8086-191f59904f9e.png)

Thanks @corepay for the heads up.
@hawkeye64 - maybe its time to think about Issue Templates for this Repo (and any others that might need them)
